# Ajustes del sitio. Archivo _config.yml
title: "Servicios de Limpieza Profesional | AB Limpieza"
description: "AB Limpieza ofrece servicios de limpieza profesional en el Baix Llobregat, Molins de Rei y alrededores."
baseurl: "" # Si el sitio web está en un subdirectorio, como p. ej. "/blog"
url: "https://webABlimpieza.com.github.io" # La URL de su sitio sin el subdirectorio
author: "<a href='https://www.qe2computing.com/'>QE2 computing</a>"

# Configuración
markdown: kramdown
# theme: minima # Cambie el tema si desea usar uno diferente
paginate: 5

# Permalinks
permalink: /:categories/:title.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
  - jekyll-admin

# Optional settings
timezone: "Europe/Madrid" # Ajuste según su zona horaria
language: "es"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
