# Ajustes del sitio. Archivo _config.yml
title: "Título del sitio"
description: "Una breve descripción de su sitio web."
baseurl: "" # Si su sitio está en un subdirectorio, como p. ej. "/blog"
url: "https://su_usuario.github.io" # La URL de su sitio sin el subdirectorio
author: "Su Nombre"

# Configuración
markdown: kramdown
theme: minima # Cambie el tema si desea usar uno diferente

# Permalinks
permalink: /:categories/:title.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Optional settings
timezone: "Europe/Madrid" # Ajuste según su zona horaria
language: "es"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby